### ISSUE TITLE
XrootD client implementation

### ISSUE THREAD

**Issue by brianv0** [dCache/xrootd4j#3]
I poked around the code but didn't see any client implementations. Is there any plan for this project to provide an XrootD client implementation in java as well?

**Comment by gbehrmann** [comment]
I had hopes for a client implementation some years ago, but there was no big need and nobody else stepped up to help with working on xrootd4j. If that's something you want to help out with, I would welcome your contributions. Essentially the request and response messages need to be updated to work on the client side, and maybe a facade needs to be added to make it easy to build a connection and perform "xrootd calls".

**Comment by vkhristenko** [comment]
@gbehrmann 

Hi Gerd, my name is Viktor and I'm working on bridging Spark to ROOT (CERN's data format) to run analysis on Hadoop Stack (mainly with hdfs + spark + spark-root (JVM ROOT I/O)). https://github.com/diana-hep/spark-root
It's somwhere around the proof-of-concept stage and works quite well...

I have a rather stupid question - 1 of the things that I need is the client implementation of xrootd.
The reason is simple and you've given it in your readme:

```dCache is a distributed storage system frequently used in the Worldwide LHC Computing Grid, high energy physics, photon sciences, and other communities.
```

I think that we can help out on that front (delivering the client part), the question would be if you could provide a bit of insight for this. I'm up for a discussion via skype/anything else.

Please let me know!

VK

**Comment by gbehrmann** [comment]
Hi,

I no longer work full time at NDGF. Vincent Garonne has taken my role in the dCache team and will continue work on xrootd4j. He also needs the client part in order to implement 3rd party copy for xrootd, so I suggest you communicate. I am available for at virtual kick-off meeting if you like. I will meet Vincent in person next week during the dCache developers workshop, so I suggest we wait until the week after to give Vincent a chance to catch up.


Cheers,

/gerd

**Comment by vkhristenko** [comment]
Hi Gerd,

Thanks a lot for your reply! Yes, whatever works for you, I"m pinging relevant people from CERN.
@LucaCanali, @mevangem

VK

**Comment by vingar** [comment]
I can join the meeting. Do you have a defined date for it ?

Vincent

**Comment by gbehrmann** [comment]
@vingar, no we don't - I suggest you drive this and coordinate with the relevant people. At the workshop a third stakeholder was mentioned, so I suggest you try to get hold of them too. I will of course join the meeting too.

**Comment by vingar** [comment]
ok I'll. @vkhristenko: Should I sent a mail to Lucas ?

**Comment by vkhristenko** [comment]
I'm pining the relevant people. They should be able to make it. If not, I will connect.

@LucaCanali, @mevangem
Luca, Vag, would u guys be able to connect to this discussion and since it's relevant for eos access and I'm not yet available.

VK

**Comment by slac-srs** [comment]
Just FYI we have a java client implementation here: 

http://java.freehep.org/svn/repos/freehep/list/freehep/trunk/hepio/freehep-rootio/src/main/java/hep/io/root/daemon/xrootd/?revision=HEAD&bypassEmpty=true

It is old, and has not been actively maintained, but does work and has been in use for Fermi Gamma-Ray telescope and EXO for many years. Although it is packaged in with code for actually processing root files, the xrootd implementation is independent of the code for processing root files (except for one trivial dependency). Perhaps in can be used for inspiration, or even a starting point for something updated.

**Comment by vkhristenko** [comment]
@slac-srs,

which is 1 to 1 with what we have in here: https://github.com/diana-hep/root4j cause root4j has been cloned from freehep, renamed (a person who cloned was not able to get a reply from Tony Jonson) and updated for the past 6 month by us. 

root4j + https://github.com/diana-hep/spark-root work quite well at this point for reading ROOT files. 
Even more complex files coming from CMS experiment.

VK

**Comment by alrossi** [comment]
We have no further plans to develop a Java client for xrootd, so I am closing this request.
